import type { Topic } from './types';
import { AlgorithmIcon, ProgrammingIcon, DataRepresentationIcon, HardwareIcon, SoftwareIcon, NetworkIcon, SecurityIcon, EthicsIcon } from './components/Icons';

export const TOPICS: Topic[] = [
  // --- THEME A: CONCEPTS OF COMPUTER SCIENCE ---
  {
    id: 'a1-computer-fundamentals',
    title: 'A1: Computer Fundamentals',
    description: 'Hardware, software, and low-level data representation.',
    Icon: HardwareIcon,
    color: 'from-amber-500 to-yellow-400',
    subTopics: [
        { id: 'a1-1-1', title: 'CPU Components', prompt: 'For an IB CS student, describe the functions and interactions of the main CPU components: ALU, CU, and registers (IR, PC, MAR, MDR, AC).' },
        { id: 'a1-1-2', title: 'Role of a GPU', prompt: 'Describe the role of a GPU and the architecture that makes it suitable for complex computations like video games and AI for an IB CS student.' },
        { id: 'a1-1-3', title: 'CPU vs GPU (HL)', prompt: 'For an IB HL CS student, explain the differences between a CPU and a GPU in terms of their design philosophies, core architecture, and usage scenarios.' },
        { id: 'a1-1-4', title: 'Primary Memory', prompt: 'For an IB CS student, explain the purposes of different types of primary memory: RAM, ROM, cache (L1, L2, L3), and registers.' },
        { id: 'a1-1-5', title: 'Fetch-Decode-Execute Cycle', prompt: 'Describe the fetch, decode, and execute cycle for an IB CS student, including the interaction between memory and registers via the address, data, and control buses.' },
        // FIX: Corrected a typo in the object key, changing `id::` to `id:`.
        { id: 'a1-1-6', title: 'Pipelining (HL)', prompt: 'For an IB HL CS student, describe the process of pipelining in multi-core architectures to improve system performance.' },
        { id: 'a1-1-7', title: 'Secondary Memory', prompt: 'For an IB CS student, describe internal and external types of secondary memory storage, such as SSD, HDD, and optical drives, and the scenarios where they are used.' },
        { id: 'a1-1-8', title: 'Compression', prompt: 'Describe the concept of compression for an IB CS student, explaining the difference between lossy and lossless compression methods.' },
        { id: 'a1-1-9', title: 'Cloud Computing Services', prompt: 'Describe the different types of services in cloud computing for an IB CS student: SaaS, PaaS, and IaaS.' },
        { id: 'a1-2-0', title: 'Binary Adventure', prompt: 'What is Binary? Why do computers use it?' },
        { id: 'a1-2-1', title: 'Data Representation', prompt: 'Describe for an IB CS student the principal methods of representing integer data in binary and hexadecimal, and how to convert between them and decimal.' },
        { id: 'a1-2-2', title: 'Storing Data in Binary', prompt: 'Explain for an IB CS student how binary is used to store various data types, including integers, strings, characters, images, and audio.' },
        { id: 'a1-2-3', title: 'Logic Gates', prompt: 'Describe the purpose and use of the main logic gates for an IB CS student: AND, OR, NOT, NAND, NOR, XOR, XNOR.' },
        { id: 'a1-2-4', title: 'Truth Tables', prompt: 'Explain for an IB CS student how to construct and analyse truth tables to predict the output of simple logic circuits.' },
        { id: 'a1-2-5', title: 'Logic Diagrams', prompt: 'Explain for an IB CS student how to construct logic diagrams using standard gate symbols to represent Boolean expressions.' },
        { id: 'a1-3-1', title: 'Role of Operating Systems', prompt: 'Describe the role of operating systems in abstracting hardware complexities to manage system resources for an IB CS student.' },
        { id: 'a1-3-2', title: 'Functions of an OS', prompt: 'Describe the key functions of an operating system for an IB CS student, including memory management, scheduling, and providing a GUI.' },
        { id: 'a1-3-3', title: 'Scheduling Approaches', prompt: 'Compare different CPU scheduling approaches for an IB CS student: first-come first-served, round robin, and priority scheduling.' },
        { id: 'a1-3-4', title: 'Polling & Interrupts', prompt: 'Evaluate the use of polling and interrupt handling for an IB CS student, considering CPU overhead, latency, and event predictability.' },
        { id: 'a1-3-5', title: 'Multitasking (HL)', prompt: 'For an IB HL CS student, explain the role of the operating system in managing multitasking and resource allocation, including the challenges of deadlock.' },
        { id: 'a1-3-6', title: 'Control System Components (HL)', prompt: 'Describe the use of control system components for an IB HL CS student: sensors, actuators, and the input-process-output-feedback mechanism.' },
        { id: 'a1-3-7', title: 'Control System Applications (HL)', prompt: 'Explain the use of control systems in a range of real-world applications for an IB HL CS student, such as autonomous vehicles or home thermostats.' },
        { id: 'a1-4-1', title: 'Interpreters & Compilers (HL)', prompt: 'For an IB HL CS student, evaluate the translation processes of interpreters and compilers, comparing their mechanics, use-cases, and error detection.' },
    ],
  },
  {
    id: 'a2-networks',
    title: 'A2: Networks',
    description: 'Principles of data transmission and network architecture.',
    Icon: NetworkIcon,
    color: 'from-blue-500 to-indigo-400',
    subTopics: [
        { id: 'a2-1-1', title: 'Network Types', prompt: 'Describe the purpose and characteristics of different networks for an IB CS student: LAN, WAN, PAN, and VPN.' },
        { id: 'a2-1-2', title: 'Digital Infrastructures', prompt: 'Describe the purpose, benefits, and limitations of modern digital infrastructures like the internet and cloud computing for an IB CS student.' },
        { id: 'a2-1-3', title: 'Network Devices', prompt: 'Describe the function of common network devices for an IB CS student, such as routers, switches, firewalls, and modems.' },
        { id: 'a2-1-4', title: 'Network Protocols', prompt: 'Describe the network protocols used for transport and application for an IB CS student, including TCP, UDP, HTTP, and HTTPS.' },
        { id: 'a2-1-5', title: 'TCP/IP Model (HL)', prompt: 'For an IB HL CS student, describe the function of the four layers of the TCP/IP model: Application, Transport, Internet, and Network Interface.' },
        { id: 'a2-2-1', title: 'Network Topologies', prompt: 'Describe the functions and practical applications of star, mesh, and hybrid network topologies for an IB CS student.' },
        { id: 'a2-2-2', title: 'Function of Servers (HL)', prompt: 'Describe the function of different types of servers for an IB HL CS student, such as DNS, DHCP, file, and web servers.' },
        { id: 'a2-2-3', title: 'Networking Models', prompt: 'Compare and contrast client-server and peer-to-peer networking models for an IB CS student, discussing their benefits and drawbacks.' },
        { id: 'a2-2-4', title: 'Network Segmentation', prompt: 'Explain the concepts and applications of network segmentation, subnetting, and VLANs for an IB CS student.' },
        { id: 'a2-3-1', title: 'IP Addressing', prompt: 'Describe different types of IP addressing for an IB CS student, including the distinction between IPv4 vs IPv6, and public vs private addresses.' },
        { id: 'a2-3-2', title: 'Transmission Media', prompt: 'Compare types of media for data transmission for an IB CS student, including fibre optic, twisted pair cables, and wireless.' },
        { id: 'a2-3-3', title: 'Packet Switching', prompt: 'Explain for an IB CS student how packet switching is used to send data across a network, including the role of switches and routers.' },
        { id: 'a2-3-4', title: 'Routing (HL)', prompt: 'For an IB HL CS student, explain how static routing and dynamic routing move data across local area networks.' },
        { id: 'a2-4-1', title: 'Firewalls', prompt: 'Discuss the effectiveness of firewalls at protecting a network for an IB CS student, including their strengths and limitations.' },
        { id: 'a2-4-2', title: 'Network Vulnerabilities (HL)', prompt: 'For an IB HL CS student, describe common network vulnerabilities such as DDoS, phishing, malware, and SQL injection.' },
        { id: 'a2-4-3', title: 'Network Countermeasures (HL)', prompt: 'For an IB HL CS student, describe common network countermeasures such as MFA, IDS/IPS, VPNs, and input validation.' },
        { id: 'a2-4-4', title: 'Encryption & Certificates', prompt: 'Describe the process of encryption for an IB CS student, including symmetric vs asymmetric cryptography and the role of digital certificates.' },
    ],
  },
  {
    id: 'a3-databases',
    title: 'A3: Databases',
    description: 'Database design, structures, and operations.',
    Icon: SecurityIcon,
    color: 'from-rose-500 to-red-400',
    subTopics: [
        { id: 'a3-1-1', title: 'Relational Databases', prompt: 'Explain the features, benefits, and limitations of a relational database for an IB CS student.' },
        { id: 'a3-2-1', title: 'Database Schemas', prompt: 'Describe the three levels of database schemas for an IB CS student: conceptual, logical, and physical.' },
        { id: 'a3-2-2', title: 'Entity Relationship Diagrams', prompt: 'Explain for an IB CS student how to construct Entity Relationship Diagrams (ERDs), including the roles of cardinality and modality.' },
        { id: 'a3-2-3', title: 'Relational Data Types', prompt: 'Outline the different data types used in relational databases for an IB CS student and the importance of data type consistency.' },
        { id: 'a3-2-4', title: 'Constructing Tables', prompt: 'Explain how to construct tables for relational databases for an IB CS student, showing relationships using primary and foreign keys.' },
        { id: 'a3-2-5', title: 'Normal Forms', prompt: 'Explain the difference between First (1NF), Second (2NF), and Third (3NF) normal forms for an IB CS student.' },
        { id: 'a3-2-6', title: 'Database Normalization to 3NF', prompt: 'Explain for an IB CS student how to construct a database normalized to 3NF for a real-world scenario like school management.' },
        { id: 'a3-2-7', title: 'Denormalization', prompt: 'Evaluate the need for denormalizing databases for an IB CS student, discussing the trade-off between performance and data redundancy.' },
        { id: 'a3-3-1', title: 'SQL Language Types', prompt: 'Outline the differences between data definition language (DDL) and data manipulation language (DML) within SQL for an IB CS student.' },
        { id: 'a3-3-2', title: 'SQL Queries', prompt: 'Explain for an IB CS student how to construct SQL queries between two tables using joins, filtering (WHERE), and ordering (ORDER BY).' },
        { id: 'a3-3-3', title: 'Updating Data with SQL', prompt: 'Explain how SQL can be used to update data in a database for an IB CS student, using INSERT, UPDATE, and DELETE.' },
        { id: 'a3-3-4', title: 'SQL Aggregate Functions (HL)', prompt: 'For an IB HL CS student, explain how to construct calculations within a database using SQL\'s aggregate functions (e.g., COUNT, SUM, AVG).' },
        { id: 'a3-3-5', title: 'Database Views (HL)', prompt: 'Describe the difference between virtual and materialized database views for an IB HL CS student.' },
        { id: 'a3-3-6', title: 'Database Transactions (HL)', prompt: 'For an IB HL CS student, describe how transactions maintain data integrity in a database, with reference to the ACID properties.' },
        { id: 'a3-4-1', title: 'Alternative Databases (HL)', prompt: 'Outline the different types of databases as approaches to storing data for an IB HL CS student, such as NoSQL, cloud, and in-memory databases.' },
        { id: 'a3-4-2', title: 'Data Warehouses (HL)', prompt: 'Explain the primary objectives of data warehouses in data management and business intelligence for an IB HL CS student.' },
        { id: 'a3-4-3', title: 'OLAP & Data Mining (HL)', prompt: 'For an IB HL CS student, explain the role of online analytical processing (OLAP) and data mining for business intelligence.' },
        { id: 'a3-4-4', title: 'Distributed Databases (HL)', prompt: 'Describe the features of distributed databases for an IB HL CS student, including concurrency control, replication, and fault tolerance.' },
    ],
  },
  {
    id: 'a4-machine-learning',
    title: 'A4: Machine Learning',
    description: 'ML principles, applications, and ethical considerations.',
    Icon: EthicsIcon,
    color: 'from-lime-500 to-teal-400',
    subTopics: [
        { id: 'a4-1-1', title: 'Types of Machine Learning', prompt: 'Describe the main types of machine learning for an IB CS student: supervised, unsupervised, reinforcement, and deep learning, with real-world applications.' },
        { id: 'a4-1-2', title: 'Hardware for ML', prompt: 'Describe the hardware requirements for various machine learning scenarios for an IB CS student, from standard laptops to advanced infrastructure like GPUs and TPUs.' },
        { id: 'a4-2-1', title: 'Data Cleaning (HL)', prompt: 'Describe the significance of data cleaning in data preprocessing for an IB HL CS student, including techniques for handling outliers and missing data.' },
        { id: 'a4-2-2', title: 'Feature Selection (HL)', prompt: 'Describe the role of feature selection in machine learning for an IB HL CS student, including filter and wrapper methods.' },
        { id: 'a4-2-3', title: 'Dimensionality Reduction (HL)', prompt: 'Describe the importance of dimensionality reduction for an IB HL CS student and the "curse of dimensionality".' },
        { id: 'a4-3-1', title: 'Linear Regression (HL)', prompt: 'Explain for an IB HL CS student how linear regression is used to predict continuous outcomes.' },
        { id: 'a4-3-2', title: 'Classification Techniques (HL)', prompt: 'Explain for an IB HL CS student how classification techniques like K-Nearest Neighbours (K-NN) and decision trees are used to predict discrete outcomes.' },
        { id: 'a4-3-3', title: 'Hyperparameter Tuning (HL)', prompt: 'Explain the role of hyperparameter tuning when evaluating supervised learning algorithms for an IB HL CS student, including metrics like accuracy, precision, and recall.' },
        { id: 'a4-3-4', title: 'Clustering Techniques (HL)', prompt: 'Describe for an IB HL CS student how clustering techniques in unsupervised learning are used to group data based on feature similarities.' },
        { id: 'a4-3-5', title: 'Association Rule Learning (HL)', prompt: 'Describe for an IB HL CS student how association rule learning is used to uncover relations between attributes in large data sets, e.g., market basket analysis.' },
        { id: 'a4-3-6', title: 'Reinforcement Learning (HL)', prompt: 'Describe for an IB HL CS student how an agent learns to make decisions by interacting with its environment in reinforcement learning.' },
        { id: 'a4-3-7', title: 'Genetic Algorithms (HL)', prompt: 'Describe the application of genetic algorithms in various real-world situations for an IB HL CS student, using the "travelling salesperson problem" as an example.' },
        { id: 'a4-3-8', title: 'Artificial Neural Networks (HL)', prompt: 'Outline the structure and function of Artificial Neural Networks (ANNs) for an IB HL CS student, including single and multi-layer perceptrons.' },
        { id: 'a4-3-9', title: 'Convolutional Neural Networks (HL)', prompt: 'Describe for an IB HL CS student how Convolutional Neural Networks (CNNs) are designed to adaptively learn spatial hierarchies of features in images.' },
        { id: 'a4-3-10', title: 'Model Selection (HL)', prompt: 'Explain the importance of model selection and comparison in machine learning for an IB HL CS student.' },
        { id: 'a4-4-1', title: 'Ethical Implications of ML', prompt: 'Discuss the ethical implications of machine learning in real-world scenarios for an IB CS student, including algorithmic fairness, bias, privacy, and transparency.' },
        { id: 'a4-4-2', title: 'Ethics of Emerging Tech', prompt: 'Discuss for an IB CS student the ethical aspects of the increasing integration of computer technologies into daily life, such as quantum computing and augmented reality.' },
    ],
  },
  // --- THEME B: COMPUTATIONAL THINKING & PROBLEM-SOLVING ---
  {
    id: 'b1-computational-thinking',
    title: 'B1: Computational Thinking',
    description: 'Fundamental approaches to problem specification and decomposition.',
    Icon: AlgorithmIcon,
    color: 'from-emerald-500 to-green-400',
    subTopics: [
      { id: 'b1-1-1', title: 'Problem Specification', prompt: 'Explain how to construct a detailed problem specification for an IB Computer Science student, including constraints, objectives, and evaluation criteria.' },
      { id: 'b1-1-2', title: 'Fundamental Concepts', prompt: 'Describe the fundamental concepts of computational thinking for an IB CS student: abstraction, algorithmic design, decomposition, and pattern recognition.' },
      { id: 'b1-1-3', title: 'Applying CT', prompt: 'Explain how applying computational thinking to fundamental concepts is used to approach and solve problems in computer science for an IB CS student.' },
      { id: 'b1-1-4', title: 'Flowcharts', prompt: 'Explain how to trace flowcharts for a range of programming algorithms for an IB CS student, including the standard symbols for Input/Output, Process, Decision, and Start/End.' },
    ],
  },
  {
    id: 'b2-programming',
    title: 'B2: Programming',
    description: 'Core programming fundamentals, data structures, and algorithms.',
    Icon: ProgrammingIcon,
    color: 'from-fuchsia-500 to-pink-400',
    subTopics: [
      { id: 'b2-1-1', title: 'Variables & Data Types', prompt: 'Explain for an IB CS student the use of global and local variables, and describe the common data types: Boolean, char, decimal, integer, string.' },
      { id: 'b2-1-2', title: 'Substring Manipulation', prompt: 'Explain for an IB CS student how to construct programs that can extract and manipulate substrings.' },
      { id: 'b2-1-3', title: 'Exception Handling', prompt: 'Describe for an IB CS student how programs use common exception handling techniques (try/catch or try/except) to manage errors.' },
      { id: 'b2-1-4', title: 'Debugging Techniques', prompt: 'Explain for an IB CS student how to construct and use common debugging techniques, such as trace tables, breakpoints, and print statements.' },
      { id: 'b2-2-1', title: 'Static vs Dynamic Structures', prompt: 'Compare static and dynamic data structures for an IB CS student, including their underlying mechanisms for memory allocation and resizing.' },
      { id: 'b2-2-2', title: 'Arrays & Lists', prompt: 'Explain how to construct programs that apply one-dimensional and two-dimensional arrays/Lists for an IB CS student.' },
      { id: 'b2-2-3', title: 'Stacks (LIFO)', prompt: 'Explain the concept of a stack as a "last in, first out" (LIFO) data structure for an IB CS student, including the operations push, pop, and isEmpty.' },
      { id: 'b2-2-4', title: 'Queues (FIFO)', prompt: 'Explain the concept of a queue as a "first in, first out" (FIFO) data structure for an IB CS student, including the operations enqueue and dequeue.' },
      { id: 'b2-3-1', title: 'Sequence', prompt: 'Explain for an IB CS student how to construct programs that implement the correct sequence of code instructions to meet program objectives.' },
      { id: 'b2-3-2', title: 'Selection', prompt: 'Explain for an IB CS student how to construct programs utilizing selection structures (if, else, else if) to control program flow.' },
      { id: 'b2-3-3', title: 'Looping', prompt: 'Explain for an IB CS student how to construct programs that utilize looping structures (counted and conditional) to perform repeated actions.' },
      { id: 'b2-3-4', title: 'Functions & Modularization', prompt: 'Explain for an IB CS student how to construct functions and use modularization to create well-structured, reusable code.' },
      { id: 'b2-4-1', title: 'Algorithm Efficiency (Big O)', prompt: 'Describe the efficiency of specific algorithms by calculating their Big O notation to analyse their scalability for an IB CS student.' },
      { id: 'b2-4-2', title: 'Search Algorithms', prompt: 'Construct and trace algorithms to implement a linear search and a binary search for an IB CS student, and describe the differences in their efficiency.' },
      { id: 'b2-4-3', title: 'Sort Algorithms', prompt: 'Construct and trace algorithms to implement bubble sort and selection sort for an IB CS student, evaluating their time and space complexities.' },
      { id: 'b2-4-4', title: 'Recursion Fundamentals (HL)', prompt: 'Explain the fundamental concept of recursion and its applications in programming for an IB HL student, including its advantages and limitations.' },
      { id: 'b2-4-5', title: 'Recursive Algorithms (HL)', prompt: 'Explain for an IB HL student how to construct and trace simple, non-branching recursive algorithms in a programming language.' },
      { id: 'b2-5-1', title: 'File Processing', prompt: 'Explain for an IB CS student how to construct code to perform file-processing operations on text files (read, write, append).' },
    ],
  },
  {
    id: 'b3-oop',
    title: 'B3: Object-Oriented Programming',
    description: 'The OOP paradigm for solving complex problems.',
    Icon: SoftwareIcon,
    color: 'from-sky-500 to-cyan-400',
    subTopics: [
      { id: 'b3-1-1', title: 'Fundamentals of OOP', prompt: 'Evaluate the fundamentals of OOP for an IB CS student: classes, objects, inheritance, encapsulation, and polymorphism.' },
      { id: 'b3-1-2', title: 'Class Design (UML)', prompt: 'Explain for an IB CS student how to construct a design of classes, their methods and behaviour, using Unified Modeling Language (UML) class diagrams.' },
      { id: 'b3-1-3', title: 'Static vs Non-Static', prompt: 'Distinguish between static and non-static variables and methods for an IB CS student, including their usage and scope.' },
      { id: 'b3-1-4', title: 'Classes & Objects', prompt: 'Explain for an IB CS student how to construct code to define classes and instantiate objects, including the role of constructors.' },
      { id: 'b3-1-5', title: 'Encapsulation & Info Hiding', prompt: 'Explain and apply the concepts of encapsulation and information hiding in OOP for an IB CS student, including the use of private/public access modifiers.' },
      { id: 'b3-2-1', title: 'Inheritance (HL)', prompt: 'For an IB HL student, explain and apply the concept of inheritance in OOP to promote code reusability, describing the relationship between parent and child classes.' },
      { id: 'b3-2-2', title: 'Polymorphism (HL)', prompt: 'For an IB HL student, explain how to construct code to model polymorphism and its various forms, such as method overriding.' },
      { id: 'b3-2-3', title: 'Abstraction (HL)', prompt: 'Explain the concept of abstraction in OOP for an IB HL student, including the use of abstract classes to establish common interfaces.' },
      { id: 'b3-2-4', title: 'Composition & Aggregation (HL)', prompt: 'Explain the role of composition and aggregation in class relationships for an IB HL student.' },
      { id: 'b3-2-5', title: 'Design Patterns (HL)', prompt: 'Explain commonly used design patterns in OOP for an IB HL student, such as singleton, factory, and observer.' },
    ],
  },
  {
    id: 'b4-adts-hl',
    title: 'B4: Abstract Data Types (HL)',
    description: 'Advanced data structures and their appropriate uses.',
    Icon: DataRepresentationIcon,
    color: 'from-purple-500 to-violet-400',
    subTopics: [
      { id: 'b4-1-1', title: 'Properties of ADTs (HL)', prompt: 'Explain the properties and purpose of Abstract Data Types (ADTs) in programming for an IB HL Computer Science student.' },
      { id: 'b4-1-2', title: 'Linked Lists (HL)', prompt: 'For an IB HL student, evaluate linked lists (singly, doubly, circular) and describe their basic operations: insertion, deletion, and traversal.' },
      { id: 'b4-1-3', title: 'Constructing Linked Lists (HL)', prompt: 'Explain for an IB HL student how to construct and apply linked lists (singly, doubly, circular) to solve problems.' },
      { id: 'b4-1-3-interactive', title: 'Interactive Linked List Practice', prompt: 'Practice linked list operations like insertion and deletion.' },
      { id: 'b4-1-4', title: 'Binary Search Trees (BSTs) (HL)', prompt: 'For an IB HL student, explain the structures and properties of Binary Search Trees (BSTs), including insert, delete, and traversal operations.' },
      { id: 'b4-1-4-interactive', title: 'Interactive BST Practice', prompt: 'Practice Binary Search Tree operations like insertion and search.' },
      { id: 'b4-1-5', title: 'Sets as an ADT (HL)', prompt: 'Explain for an IB HL student how to construct and apply sets as an ADT, including the operations of union, intersection, and difference.' },
      { id: 'b4-1-6', title: 'Hash Tables (HL)', prompt: 'Explain the core principles of hash tables as an ADT for an IB HL student, including hashing functions, collision resolution strategies, and load factors.' },
    ],
  },
];